services:
    app:
        shm_size: '1000000000'
        build:
            context: ./app
        tty: true
    nginx:
        build: ./nginx
        tty: true
        links:
            - app
        ports:
            - '8844:80'
